### ISSUE TITLE
Remis master To-do list

### ISSUE THREAD

**Issue by ewels** [nf-core/neutronstar#1]
_From @remiolsen on December 11, 2017 17:4_

For transparency, here's my "design document"

------
**Main requirements**
- [x] Nextflow? yes
- [x] Supernova running in `$SNIC_TMP` (Irma compatible?)
    - [x] 1.20 compatible — multiple input parameter assemblies
    - ~[ ] Use nextflow publishdata in stead of rsync~ couldn't make it work. Use rsync!
    - [x] Make a this optional
- [x] Rsync supernova assembly back to workdir
- [x] supernova mkoutput - pseudohap, megabubbles
    - [x] gunzip
    - [x] parameter of additional outputs — always output .phased.fasta
    - [x] parameter for minimum length
- [x] QUAST
    - [x] make it run on Irma
- [x] BUSCO
    - [x] UPPMAX — beforeScript
- [x] MultiQC
   - [x] Needs testing
- [x] support for `--no-preflight` flag
- [x] Documentation
    - [x] Readme.md
- [x] dump software versions & commands that were run
- [x] Send mail when done pipeline is finished
- [x] Clean up and generalize the configs
     - [x] Common HPC config
     - [x] Common Uppmax config
     - [x] Make a general local run config
- [x] Release tags

**Docker / Singularity**
- [x] Supernova ~(copyright issues?)~
- [x] Quast
- [x] BUSCO
- [x] Script for automatic singularity/docker download / installation

**NX script**
- [x] input configuration:
    - [x] id
         - [x] fastqs
         - [x] sample
         - [x] maxreads
         - [x] bcfrac
    - [x] genomesize
- [x] memory parameter
- [x] cpu parameter
- [x] make Longranger / fastqc optional

**Input_validation**
   - [x] id — only numbers, letters, dash, and underscore allowed
   - [x] bcfrac (0,1)
   - [x] maxreads - num

**MultiQC**
- [x] Fix when having empty molecule.yaml files
- [x] Does having “ASSEMBLER_CS” folders break multiqc?
- [x] Fix QUAST module. It breaks when running with -s option

**Testing**
- [x] Test data ~from NA12878 run.~
- [x] Travis-CI integration

**Could haves**
- [ ] ~Tigmint evaluation~
- [x] Delivery template mail / output folder structure
- [ ] ~BWA align~
    - [ ] ~picard-tools~
    - [ ] ~remove dups~
    - [ ] ~collectinsertsize~
- [ ] ~qaTools-singularity~
- [ ] ~FRC-singularity~
- [x] BUSCOv2 datasets in config
    - [x] auto-script to download datasets

_Copied from original issue: SciLifeLab/NGI-NeutronStar#3_

**Comment by ewels** [comment]
Re: software version numbers - just a note not to copy the RNA pipeline for this, but instead I'd recommend having a dedicated process as in the [ChIPseq pipeline](https://github.com/SciLifeLab/NGI-ChIPseq/blob/c29361b69fcd831def101d02a58a57aa58ca9746/main.nf#L809-L833) (and others). The RNAseq approach has been more of a pain.
